services:
  - type: web
    name: app-consumo-de-chapa-codigo-peca
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: AUTH_ENABLED
        value: "1"
      - key: APP_USER
        value: admin
      - key: APP_PASSWORD
        value: troque-esta-senha
      - key: KERF_MM
        value: "4"
      - key: META_APROVEITAMENTO
        value: "0.95"
      - key: PERMITE_GIRAR_90
        value: "1"
